-- ============================================================================
-- seed_curriculum.sql — generated from src/data/curriculum.ts (createSeedData)
--
-- The client cannot write curriculum tables under RLS (SELECT-only policies).
-- Run this ONCE in the Supabase SQL Editor (or via the service role) so the
-- app can reference module/topic/subtopic ids when syncing user progress.
-- Safe to re-run: all inserts use ON CONFLICT (id) DO NOTHING.
-- ============================================================================

BEGIN;

-- Module: Web Foundations & Generic Basics
INSERT INTO public.modules (id, name, weight, phase, phase_order, curriculum_version) VALUES ('m1', 'Web Foundations & Generic Basics', 15, 'Generic Training', 1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m1-t1', 'm1', 'HTML5 & Document Structure', 'beginner', 2.5, ARRAY['Use semantic HTML elements for accessible documents', 'Build and validate HTML forms', 'Apply HTML5 validation attributes and custom JavaScript validation'], '{}'::text[], ARRAY['Create a semantic blog layout', 'Build a registration form with client-side validation'], 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m1-t1-s1', 'm1-t1', 'Semantic elements', 40, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m1-t1-s2', 'm1-t1', 'Forms & input types', 50, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m1-t1-s3', 'm1-t1', 'Form validation (HTML5 + JS)', 60, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m1-t2', 'm1', 'CSS3 Layout Engines', 'beginner', 3, ARRAY['Calculate selector specificity', 'Position elements using the box model', 'Build responsive layouts with Flexbox and Grid'], ARRAY['m1-t1'], ARRAY['Recreate a responsive card layout with Flexbox', 'Build a full-page dashboard using CSS Grid'], 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m1-t2-s1', 'm1-t2', 'Selectors & specificity', 30, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m1-t2-s2', 'm1-t2', 'Box model & positioning', 40, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m1-t2-s3', 'm1-t2', 'Flexbox layouts', 50, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m1-t2-s4', 'm1-t2', 'CSS Grid layouts', 60, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m1-t3', 'm1', 'JavaScript Core', 'beginner-intermediate', 3.5, ARRAY['Select and modify DOM elements', 'Use ES6+ syntax including arrow functions and destructuring', 'Handle events with proper propagation control'], ARRAY['m1-t2'], ARRAY['Build a dynamic to-do list with add/delete/complete', 'Implement a tabbed interface with event delegation'], 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m1-t3-s1', 'm1-t3', 'DOM manipulation (querySelector, events)', 60, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m1-t3-s2', 'm1-t3', 'ES6+ features (let/const, arrow, destructuring)', 70, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m1-t3-s3', 'm1-t3', 'Event handling, propagation & delegation', 80, 3) ON CONFLICT (id) DO NOTHING;

-- Module: FA1 — Java Programming & OOPs
INSERT INTO public.modules (id, name, weight, phase, phase_order, curriculum_version) VALUES ('m2', 'FA1 — Java Programming & OOPs', 45, 'Full Java Learning Path', 2, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t1', 'm2', 'Java Environment & First Program', 'beginner', 2, ARRAY['Explain the JVM, JDK, and JRE roles in Java development', 'Compile and execute a simple Java program from the command line', 'Organise code using packages and import statements', 'Describe the significance of each part of the main method signature'], '{}'::text[], ARRAY['Set up JDK and verify with `java -version` and `javac -version`', 'Write a HelloWorld program with a custom package name', 'Create a second class in the same package and call its method from main', 'Experiment: What happens if you remove `static` from main? Document the error.'], 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t1-s1', 'm2-t1', 'JVM, JDK, JRE architecture explained', 30, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t1-s2', 'm2-t1', 'Writing, compiling & running your first Java program', 40, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t1-s3', 'm2-t1', 'Package & import statements', 20, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t1-s4', 'm2-t1', 'Understanding public static void main(String[])', 30, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t2', 'm2', 'Java Primitives, Variables & Type System', 'beginner', 2.5, ARRAY['Differentiate between the 8 primitive types and their memory sizes', 'Declare, initialise, and reassign variables with proper naming conventions', 'Perform implicit and explicit type casts correctly', 'Use the final keyword to declare compile-time constants'], ARRAY['m2-t1'], ARRAY['Create variables of each primitive type and print their min/max values using wrapper constants', 'Write a temperature converter (Celsius ↔ Fahrenheit) using explicit casting', 'Identify and fix type-mismatch compilation errors in provided code snippets', 'Declare a final double PI = 3.14159 and attempt to reassign — observe the error'], 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t2-s1', 'm2-t2', 'Primitive types: byte, short, int, long, float, double, char, boolean', 45, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t2-s2', 'm2-t2', 'Variable declaration, naming conventions & scope', 35, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t2-s3', 'm2-t2', 'Type casting: implicit (widening) & explicit (narrowing)', 45, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t2-s4', 'm2-t2', 'Constants with the final keyword', 25, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t3', 'm2', 'Operators & Expressions', 'beginner', 2, ARRAY['Evaluate expressions using Java operator precedence rules', 'Use relational and logical operators to build boolean conditions', 'Apply bitwise operators for low-level bit manipulation', 'Write concise conditional logic with the ternary operator'], ARRAY['m2-t2'], ARRAY['Evaluate complex expressions step-by-step; verify with code', 'Write a method that checks if a year is a leap year using logical operators', 'Use bitwise XOR to swap two integers without a temporary variable', 'Rewrite a chain of if-else statements using nested ternary operators (then discuss readability)'], 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t3-s1', 'm2-t3', 'Arithmetic, relational & logical operators', 30, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t3-s2', 'm2-t3', 'Bitwise operators & shift operations', 40, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t3-s3', 'm2-t3', 'Operator precedence & associativity', 20, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t3-s4', 'm2-t3', 'Short-circuit evaluation & ternary (? :) operator', 30, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t4', 'm2', 'Control Flow: Selection & Iteration', 'beginner', 3, ARRAY['Write correct if-else and switch-case selection statements', 'Choose the appropriate loop construct for a given scenario', 'Control loop execution with break and continue, including labelled variants', 'Debug common iteration errors'], ARRAY['m2-t3'], ARRAY['Implement a number-guessing game using while loops and if-else', 'Print a multiplication table (1–10) using nested for loops', 'Use a labelled break to exit from an outer loop', 'Write a switch expression that returns a String (Java 14+ arrow syntax)'], 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t4-s1', 'm2-t4', 'if-else, else-if, switch-case (with arrow syntax)', 45, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t4-s2', 'm2-t4', 'for loop, enhanced for-each, while, do-while', 55, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t4-s3', 'm2-t4', 'break, continue & labelled statements', 30, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t4-s4', 'm2-t4', 'Common loop patterns & pitfalls (off-by-one, infinite loops)', 50, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t5', 'm2', 'Arrays in Java', 'beginner', 2.5, ARRAY['Create, initialise, and iterate over single and multi-dimensional arrays', 'Use the Arrays utility class for common operations', 'Distinguish between rectangular and jagged 2D arrays', 'Write methods that accept variable-length argument lists'], ARRAY['m2-t2', 'm2-t4'], ARRAY['Reverse an array in-place without using a second array', 'Implement a method to find the second-largest element in an int array', 'Create a jagged 2D array representing Pascal''s Triangle (first 5 rows)', 'Write a varargs method that computes the average of any number of doubles'], 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t5-s1', 'm2-t5', 'Single-dimensional arrays: declaration, initialisation, traversal', 40, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t5-s2', 'm2-t5', 'Multi-dimensional arrays (rectangular & jagged)', 45, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t5-s3', 'm2-t5', 'java.util.Arrays utility class (sort, binarySearch, fill, copyOf)', 35, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t5-s4', 'm2-t5', 'Variable-length arguments (varargs)', 30, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t6', 'm2', 'Methods: Declaration, Overloading & Recursion', 'beginner-intermediate', 3, ARRAY['Declare methods with correct syntax and appropriate access levels', 'Explain why Java is strictly pass-by-value', 'Overload methods differentiating by parameter count, type, and order', 'Write recursive methods and trace their call stack'], ARRAY['m2-t4'], ARRAY['Write overloaded `area` methods for circle, rectangle, and triangle', 'Implement a recursive factorial method — trace the stack for n=5', 'Write a recursive binary search and compare with an iterative version', 'Swap two integers using a method — explain why the swap doesn''t persist outside'], 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t6-s1', 'm2-t6', 'Method signature: access modifier, return type, name, parameters', 30, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t6-s2', 'm2-t6', 'Pass-by-value semantics in Java', 35, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t6-s3', 'm2-t6', 'Method overloading rules & use cases', 35, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t6-s4', 'm2-t6', 'Recursion: base case, recursive case, stack tracing', 60, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t6-s5', 'm2-t6', 'Recursion vs iteration trade-offs', 20, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t7', 'm2', 'Classes, Objects & Constructors', 'beginner-intermediate', 3.5, ARRAY['Design a Java class with fields, constructors, and instance methods', 'Distinguish between instance members and static members', 'Use constructor overloading and this() for constructor chaining', 'Create objects and interact with their state through methods'], ARRAY['m2-t1', 'm2-t2', 'm2-t6'], ARRAY['Model a BankAccount class with accountNumber, balance, and static interestRate', 'Add a copy constructor that creates a new account with the same balance', 'Use a static initializer block to load configuration values', 'Write a main method that creates 3 BankAccount objects and performs deposits/withdrawals'], 7) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t7-s1', 'm2-t7', 'Class declaration, fields, instance methods', 45, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t7-s2', 'm2-t7', 'Object instantiation with the new keyword', 30, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t7-s3', 'm2-t7', 'Constructors: default, parameterised, copy', 55, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t7-s4', 'm2-t7', 'this keyword — field shadowing, constructor chaining', 40, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t7-s5', 'm2-t7', 'Static members: variables, methods, blocks', 40, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t8', 'm2', 'String, StringBuilder & Wrapper Classes', 'beginner-intermediate', 3, ARRAY['Explain why String objects are immutable and how the String pool works', 'Write efficient string manipulation code using StringBuilder', 'Convert between primitives and wrapper objects with autoboxing', 'Parse string input into numeric types safely'], ARRAY['m2-t5', 'm2-t7'], ARRAY['Write a method that reverses each word in a sentence using StringBuilder', 'Implement an anagram checker using toCharArray, sort, and equals', 'Compare performance: String concatenation in a loop vs StringBuilder (document timing)', 'Parse a comma-separated string of numbers into an int[] using split and Integer.parseInt'], 8) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t8-s1', 'm2-t8', 'String immutability & the String pool', 35, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t8-s2', 'm2-t8', 'Essential String methods (charAt, substring, indexOf, replace, split, join)', 45, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t8-s3', 'm2-t8', 'StringBuilder & StringBuffer for mutable strings', 40, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t8-s4', 'm2-t8', 'Wrapper classes & autoboxing/unboxing', 35, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t8-s5', 'm2-t8', 'Parsing: Integer.parseInt, Double.parseDouble, etc.', 25, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t9', 'm2', 'Inheritance & the Object Superclass', 'intermediate', 3.5, ARRAY['Build inheritance hierarchies using extends with proper super() calls', 'Override methods correctly and apply the @Override annotation', 'Apply the final keyword to prevent inheritance or overriding', 'Override toString, equals, and hashCode following their contracts'], ARRAY['m2-t7'], ARRAY['Model an Employee → Manager, Developer, Intern hierarchy with a common calculatePay() method', 'Override equals and hashCode for a Student class — verify with HashSet behaviour', 'Create a final utility class (like java.lang.Math) with only static methods', 'Discuss: Why must equals and hashCode be overridden together?'], 9) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t9-s1', 'm2-t9', 'extends keyword, super() constructor call', 40, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t9-s2', 'm2-t9', 'Method overriding: @Override annotation & rules', 45, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t9-s3', 'm2-t9', 'Covariant return types', 25, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t9-s4', 'm2-t9', 'final classes & methods — design for inheritance or prohibit it', 25, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t9-s5', 'm2-t9', 'Object class: toString, equals, hashCode, and their contracts', 75, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t10', 'm2', 'Polymorphism: Runtime & Compile-Time', 'intermediate', 3, ARRAY['Distinguish between compile-time and runtime polymorphism', 'Use dynamic dispatch to write polymorphic code', 'Safely downcast references using instanceof pattern matching', 'Design classes that obey the Liskov Substitution Principle'], ARRAY['m2-t9'], ARRAY['Create a Shape hierarchy with an abstract draw() method — demonstrate polymorphic behaviour in an array', 'Write a method that accepts a List<Shape> and calls draw() on each element', 'Use pattern matching for instanceof (Java 16+) to downcast safely', 'Identify LSP violations in a provided code sample and refactor them'], 10) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t10-s1', 'm2-t10', 'Compile-time polymorphism (method overloading — revisit)', 30, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t10-s2', 'm2-t10', 'Runtime polymorphism (method overriding & dynamic dispatch)', 55, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t10-s3', 'm2-t10', 'Upcasting & downcasting with instanceof', 50, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t10-s4', 'm2-t10', 'The Liskov Substitution Principle (SOLID)', 45, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t11', 'm2', 'Encapsulation & Access Control', 'intermediate', 2, ARRAY['Choose the appropriate access modifier for each class member', 'Implement getters and setters to protect class invariants', 'Design classes that expose behaviour while hiding internal state', 'Explain how packages control visibility at the namespace level'], ARRAY['m2-t7', 'm2-t9'], ARRAY['Refactor a poorly-designed class with public fields into a properly encapsulated one', 'Implement an immutable Person class using private final fields and no setters', 'Create classes in two different packages and observe which members are accessible', 'Write a defensive copy getter that returns a copy of an internal array/list'], 11) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t11-s1', 'm2-t11', 'private, default (package-private), protected, public', 30, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t11-s2', 'm2-t11', 'Getter & setter conventions (JavaBeans pattern)', 30, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t11-s3', 'm2-t11', 'Data hiding — why expose behaviour, not data', 30, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t11-s4', 'm2-t11', 'Package-level access & module encapsulation (Java 9+)', 30, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t12', 'm2', 'Abstract Classes & Interfaces', 'intermediate', 3.5, ARRAY['Design abstract classes that define common behaviour with partial implementation', 'Implement interfaces with default and static methods', 'Identify and create functional interfaces for lambda expressions', 'Decide between abstract class and interface for a given design scenario'], ARRAY['m2-t9', 'm2-t10'], ARRAY['Design a PaymentProcessor abstract class with an abstract processPayment() and concrete logging method', 'Create a Playable interface with default methods — implement it for MusicPlayer and VideoPlayer', 'Define a functional interface Operation<T> with a method T apply(T a, T b)', 'Compare and contrast: when would you choose an abstract class over an interface?'], 12) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t12-s1', 'm2-t12', 'Abstract class: abstract methods, constructors, fields', 45, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t12-s2', 'm2-t12', 'Interface: declaration, implementation, constants', 45, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t12-s3', 'm2-t12', 'Default & static methods in interfaces (Java 8+)', 40, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t12-s4', 'm2-t12', 'Functional interfaces (SAM — Single Abstract Method)', 35, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t12-s5', 'm2-t12', 'Abstract class vs interface — when to choose which', 45, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t13', 'm2', 'Enums & Records (Java 16+)', 'intermediate', 2, ARRAY['Define enums with fields, methods, and constructors', 'Use enums in switch expressions with exhaustiveness checking', 'Declare records for transparent, immutable data carriers', 'Choose between a record and a full class based on the use case'], ARRAY['m2-t7', 'm2-t11'], ARRAY['Model an enum DayOfWeek with a method isWeekend() that returns boolean', 'Write a switch expression over a TrafficLight enum (RED, YELLOW, GREEN)', 'Declare a Point record with x and y — verify equals, hashCode, toString are auto-generated', 'Compare a record with a hand-written DTO class — what boilerplate is saved?'], 13) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t13-s1', 'm2-t13', 'Enum declaration: constants, fields, methods, constructors', 35, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t13-s2', 'm2-t13', 'EnumSet & EnumMap — specialised collections', 20, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t13-s3', 'm2-t13', 'switch with enums (exhaustiveness)', 20, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t13-s4', 'm2-t13', 'Java Records: compact constructors, accessors, equals/hashCode', 30, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t13-s5', 'm2-t13', 'When to use records vs traditional classes', 15, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t14', 'm2', 'Generics & Type Safety', 'intermediate-advanced', 3, ARRAY['Write generic classes and methods with appropriate type parameters', 'Apply bounded type parameters to constrain generic types', 'Use wildcard types for flexible API design (producer-extends, consumer-super)', 'Explain how type erasure enables generics while maintaining backward compatibility'], ARRAY['m2-t7', 'm2-t5'], ARRAY['Implement a generic Box<T> class with get/set methods', 'Write a generic method countGreaterThan(T[] array, T elem) using bounded parameters', 'Create a wildcard-based copy method: void copy(List<? super T> dest, List<? extends T> src)', 'Use reflection to inspect a generic class at runtime — observe erasure'], 14) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t14-s1', 'm2-t14', 'Generic classes, interfaces & methods', 45, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t14-s2', 'm2-t14', 'Type parameters naming conventions (T, E, K, V)', 15, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t14-s3', 'm2-t14', 'Bounded type parameters (<T extends Number>)', 35, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t14-s4', 'm2-t14', 'Wildcards: ?, ? extends T, ? super T', 50, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t14-s5', 'm2-t14', 'Type erasure & bridge methods — what happens at runtime', 35, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t15', 'm2', 'Collections Framework — List & Set', 'intermediate', 3.5, ARRAY['Choose the correct List and Set implementation based on performance requirements', 'Explain how hashCode and equals affect HashSet behaviour', 'Implement Comparable and Comparator for custom sorting', 'Traverse collections using different iteration strategies'], ARRAY['m2-t5', 'm2-t9', 'm2-t14'], ARRAY['Compare ArrayList vs LinkedList insertion/deletion performance with a benchmark loop', 'Create a Set<Student> that deduplicates based on studentId using hashCode/equals', 'Sort a list of Employee objects by salary using Comparator.comparingDouble', 'Remove duplicate words from a sentence using a LinkedHashSet (preserve order)'], 15) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t15-s1', 'm2-t15', 'List: ArrayList vs LinkedList — when to use each', 55, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t15-s2', 'm2-t15', 'Set: HashSet, LinkedHashSet, TreeSet (ordering & performance)', 55, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t15-s3', 'm2-t15', 'hashCode() & equals() contract in hash-based collections', 55, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t15-s4', 'm2-t15', 'Iteration: Iterator, ListIterator, enhanced for-each, forEach', 45, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t16', 'm2', 'Collections Framework — Map & Queue', 'intermediate', 3, ARRAY['Choose the correct Map implementation for ordering and performance needs', 'Use modern Map methods (computeIfAbsent, merge) for cleaner code', 'Implement a frequency counter using a HashMap', 'Use Deque as both stack (LIFO) and queue (FIFO)'], ARRAY['m2-t15'], ARRAY['Build a word frequency counter from a text file using HashMap with merge', 'Implement an LRU cache using LinkedHashMap (override removeEldestEntry)', 'Use a Deque to check if a string is a palindrome', 'Schedule tasks in order of priority using PriorityQueue with a custom Comparator'], 16) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t16-s1', 'm2-t16', 'Map: HashMap, LinkedHashMap, TreeMap — ordering & null handling', 55, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t16-s2', 'm2-t16', 'Map iteration: entrySet, keySet, values', 35, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t16-s3', 'm2-t16', 'computeIfAbsent, merge, putIfAbsent (Java 8+)', 45, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t16-s4', 'm2-t16', 'Queue: PriorityQueue, Deque with ArrayDeque', 45, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t17', 'm2', 'Exception Handling & Best Practices', 'intermediate', 3, ARRAY['Differentiate between checked and unchecked exceptions and use them appropriately', 'Write robust code with try-catch-finally and try-with-resources', 'Define custom exception classes that extend Exception or RuntimeException', 'Apply exception handling best practices and avoid common anti-patterns'], ARRAY['m2-t6', 'm2-t7'], ARRAY['Read a file using try-with-resources — handle FileNotFoundException and IOException separately', 'Create a custom InsufficientFundsException for the BankAccount class', 'Write a method that throws multiple checked exceptions — demonstrate caller handling', 'Review provided code for exception-handling anti-patterns: swallowing exceptions, catching Throwable, etc.'], 17) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t17-s1', 'm2-t17', 'Checked vs unchecked exceptions: when to use each', 35, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t17-s2', 'm2-t17', 'try-catch-finally — resource cleanup in finally', 40, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t17-s3', 'm2-t17', 'try-with-resources (AutoCloseable) — Java 7+', 35, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t17-s4', 'm2-t17', 'throw, throws & custom exception classes', 40, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t17-s5', 'm2-t17', 'Exception handling anti-patterns & best practices', 30, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t18', 'm2', 'Lambda Expressions & Functional Interfaces', 'intermediate-advanced', 3, ARRAY['Write lambda expressions for common functional interfaces', 'Replace anonymous inner classes with equivalent lambdas', 'Use method references for concise lambda expressions', 'Chain and compose functional operations'], ARRAY['m2-t12', 'm2-t14'], ARRAY['Replace all anonymous Comparator implementations in existing code with lambdas', 'Build a processing pipeline: filter → map → collect using Predicate and Function', 'Use method references: Class::method for static, System.out::println for instance', 'Chain Predicates with and(), or(), negate() to build complex filtering logic'], 18) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t18-s1', 'm2-t18', 'Lambda syntax: (parameters) -> expression/block', 35, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t18-s2', 'm2-t18', 'java.util.function: Consumer, Supplier, Predicate, Function', 55, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t18-s3', 'm2-t18', 'Method references: Class::staticMethod, object::instanceMethod', 45, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t18-s4', 'm2-t18', 'Composing lambdas: andThen, compose, negate, or', 45, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t19', 'm2', 'Stream API & Optional', 'intermediate-advanced', 4, ARRAY['Create and chain stream operations fluently', 'Use Collectors to aggregate stream results into collections', 'Apply reduce for custom aggregations', 'Use Optional to write null-safe code without NullPointerException'], ARRAY['m2-t15', 'm2-t18'], ARRAY['Process a list of transactions: filter by amount > 1000, group by currency, sum amounts', 'Use flatMap to flatten a list of orders into a single stream of products', 'Implement a custom collector that joins strings with a delimiter and prefix/suffix', 'Refactor a method full of null checks to use Optional fluently'], 19) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t19-s1', 'm2-t19', 'Creating streams: from collections, arrays, Stream.of, Stream.iterate', 30, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t19-s2', 'm2-t19', 'Intermediate ops: filter, map, flatMap, distinct, sorted, peek', 60, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t19-s3', 'm2-t19', 'Terminal ops: forEach, collect, reduce, count, anyMatch/allMatch/noneMatch', 55, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t19-s4', 'm2-t19', 'Collectors: toList, toSet, toMap, groupingBy, partitioningBy', 60, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t19-s5', 'm2-t19', 'Optional: creation, map, flatMap, orElse, orElseGet, orElseThrow', 35, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t20', 'm2', 'I/O, File Handling & NIO', 'intermediate-advanced', 3.5, ARRAY['Read and write text files using character streams and NIO convenience methods', 'Use Scanner to parse tokens from files or user input', 'Traverse directory trees using Files.walk and Files.find', 'Serialize and deserialize Java objects with ObjectOutputStream/ObjectInputStream'], ARRAY['m2-t17'], ARRAY['Write a program that reads a CSV file and prints statistics per column', 'Copy a large file using BufferedInputStream/BufferedOutputStream — measure performance', 'Use Files.walk to find all .txt files in a directory tree and count total lines', 'Implement a Serializable Employee class with a transient password field'], 20) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t20-s1', 'm2-t20', 'Byte streams: FileInputStream, FileOutputStream, BufferedInputStream', 45, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t20-s2', 'm2-t20', 'Character streams: FileReader, FileWriter, BufferedReader, PrintWriter', 45, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t20-s3', 'm2-t20', 'Scanner for parsing structured input', 30, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t20-s4', 'm2-t20', 'NIO.2: Path, Files, walk, find, readString/writeString (Java 11+)', 55, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t20-s5', 'm2-t20', 'Object serialization (Serializable, transient)', 35, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t21', 'm2', 'Multithreading & Concurrency Basics', 'advanced', 4, ARRAY['Create and start threads using Thread and Runnable', 'Use synchronized blocks and methods to protect shared state', 'Coordinate threads with wait/notify', 'Submit tasks to an ExecutorService and retrieve results via Future'], ARRAY['m2-t7', 'm2-t17'], ARRAY['Write a counter that increments across 5 threads — demonstrate race condition, then fix with synchronized', 'Implement producer-consumer using wait/notify on a shared Queue', 'Submit 10 Callable tasks to an ExecutorService and process the results', 'Measure throughput: single-threaded vs thread-pool for I/O-bound tasks'], 21) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t21-s1', 'm2-t21', 'Thread class & Runnable interface', 40, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t21-s2', 'm2-t21', 'Thread lifecycle: NEW, RUNNABLE, BLOCKED, WAITING, TIMED_WAITING, TERMINATED', 30, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t21-s3', 'm2-t21', 'synchronized keyword & intrinsic locks', 55, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t21-s4', 'm2-t21', 'wait, notify, notifyAll — inter-thread communication', 60, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t21-s5', 'm2-t21', 'ExecutorService, ThreadPoolExecutor & Future<T>', 55, 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t22', 'm2', 'Stack & Queue — Implementations & Use Cases', 'intermediate', 2.5, ARRAY['Implement LIFO (stack) and FIFO (queue) behaviour using ArrayDeque', 'Use PriorityQueue for priority-based ordering', 'Apply stacks to solve bracket-matching and expression evaluation problems', 'Apply queues to model breadth-first search and scheduling problems'], ARRAY['m2-t5', 'm2-t15'], ARRAY['Implement a browser forward/back navigation system using two Deque stacks', 'Check if parentheses in a string are balanced using a Stack', 'Use a Queue to implement a simple task scheduler (FIFO)', 'Evaluate a postfix expression using a Stack of integers'], 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t22-s1', 'm2-t22', 'Stack: ArrayDeque vs legacy Stack class', 40, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t22-s2', 'm2-t22', 'Queue: LinkedList, PriorityQueue, ArrayDeque', 40, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t22-s3', 'm2-t22', 'Real-world: expression evaluation, undo/redo, BFS traversal', 45, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t22-s4', 'm2-t22', 'Deque as both stack and queue', 25, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t23', 'm2', 'Searching Algorithms — Linear & Binary', 'intermediate', 2, ARRAY['Implement linear search and analyse its O(n) time complexity', 'Implement recursive and iterative binary search on sorted arrays', 'Use built-in binarySearch methods from the Java standard library', 'Select the appropriate search algorithm for a given dataset'], ARRAY['m2-t5', 'm2-t6'], ARRAY['Implement linear search — measure time on arrays of sizes 10, 100, 1000, 10000', 'Implement recursive binary search and trace the call stack for target=42', 'Search a sorted array of 1 million integers — compare linear vs binary search time', 'Use Collections.binarySearch on a sorted List<String> of names'], 23) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t23-s1', 'm2-t23', 'Linear search — O(n) iterative implementation', 25, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t23-s2', 'm2-t23', 'Binary search — iterative & recursive implementations', 45, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t23-s3', 'm2-t23', 'Arrays.binarySearch and Collections.binarySearch', 25, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t23-s4', 'm2-t23', 'Search complexity analysis & when to use each', 25, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m2-t24', 'm2', 'Sorting Algorithms — Bubble, Selection, Insertion', 'intermediate', 2.5, ARRAY['Implement bubble, selection, and insertion sort from scratch', 'Compare the time complexity of all three (O(n²)) and identify their best-case behaviours', 'Explain why built-in sorts outperform O(n²) sorts on large datasets', 'Use Arrays.sort and Collections.sort in real code'], ARRAY['m2-t5', 'm2-t6'], ARRAY['Implement all three sorts and count the number of swaps each performs on the same array', 'Measure time: sort a 10,000-element array with insertion sort vs Arrays.sort', 'Implement an optimized bubble sort that stops early if no swaps are made', 'Sort an ArrayList of Employee objects by name using Collections.sort'], 24) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t24-s1', 'm2-t24', 'Bubble sort — compare adjacent, swap', 45, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t24-s2', 'm2-t24', 'Selection sort — find min, place at front', 40, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t24-s3', 'm2-t24', 'Insertion sort — build sorted portion left-to-right', 40, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m2-t24-s4', 'm2-t24', 'Arrays.sort (Dual-Pivot Quicksort) & Collections.sort (TimSort)', 25, 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.assessments (id, module_id, name, type, estimated_hours, description, prerequisites, sort_order) VALUES ('m2-checkpoint-1', 'm2', 'Revision Checkpoint: Java Fundamentals', 'revision', 1.5, 'Covers Java Environment → Arrays → Methods. Practice coding problems on operators, control flow, arrays, and recursion. Identify weak areas before advancing to OOP.', ARRAY['m2-t1', 'm2-t2', 'm2-t3', 'm2-t4', 'm2-t5', 'm2-t6'], 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.assessments (id, module_id, name, type, estimated_hours, description, prerequisites, sort_order) VALUES ('m2-quiz-1', 'm2', 'OOP Foundations Quiz', 'quiz', 1, '20 multiple-choice questions covering classes, objects, constructors, static members, String handling, and wrapper classes.', ARRAY['m2-t7', 'm2-t8'], 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.assessments (id, module_id, name, type, estimated_hours, description, prerequisites, sort_order) VALUES ('m2-miniproject-1', 'm2', 'Mini Project: Zoo Management System', 'mini-project', 4, 'Build a Zoo Management System applying inheritance, polymorphism, and encapsulation. Includes Animal hierarchy, employee management, feeding schedules, and enclosure tracking.', ARRAY['m2-t9', 'm2-t10', 'm2-t11'], 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.assessments (id, module_id, name, type, estimated_hours, description, prerequisites, sort_order) VALUES ('m2-checkpoint-2', 'm2', 'Revision Checkpoint: OOP Mastery', 'revision', 2, 'Consolidate understanding of abstract classes, interfaces, enums, and records. Complete a set of targeted coding problems covering all OOP topics.', ARRAY['m2-t12', 'm2-t13', 'm2-t14'], 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.assessments (id, module_id, name, type, estimated_hours, description, prerequisites, sort_order) VALUES ('m2-quiz-2', 'm2', 'Collections & Generics Quiz', 'quiz', 1, '15 multiple-choice questions + 5 coding snippets on List, Set, Map, Queue, generics, and iteration patterns.', ARRAY['m2-t14', 'm2-t15', 'm2-t16'], 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.assessments (id, module_id, name, type, estimated_hours, description, prerequisites, sort_order) VALUES ('m2-miniproject-2', 'm2', 'Mini Project: Employee Payroll Processor', 'mini-project', 5, 'Process employee payroll data from a CSV file using Streams, Collections, and custom exceptions. Generate reports: department totals, top earners, tax calculations.', ARRAY['m2-t15', 'm2-t16', 'm2-t17', 'm2-t18', 'm2-t20'], 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.assessments (id, module_id, name, type, estimated_hours, description, prerequisites, sort_order) VALUES ('m2-mock', 'm2', 'Mock Assessment: Java Coding Round', 'mock', 2, 'Simulated coding interview with 3 problems: (1) algorithmic, (2) OOP design, (3) Stream API data processing. Timed at 2 hours with partial scoring.', ARRAY['m2-t17', 'm2-t19', 'm2-t21', 'm2-t22', 'm2-t23', 'm2-t24'], 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.assessments (id, module_id, name, type, estimated_hours, description, prerequisites, sort_order) VALUES ('m2-capstone', 'm2', 'Capstone Project: Library Management System', 'capstone', 8, 'Full-featured console-based Library Management System. Must implement: user management (CRUD), book catalogue with search, checkout/return flow with due dates, fine calculation, persistence to files, concurrency-safe operations, and reporting via Streams.', ARRAY['m2-t9', 'm2-t10', 'm2-t14', 'm2-t15', 'm2-t16', 'm2-t17', 'm2-t20', 'm2-t21'], 0) ON CONFLICT (id) DO NOTHING;

-- Module: FA2 — Relational Databases & SQL
INSERT INTO public.modules (id, name, weight, phase, phase_order, curriculum_version) VALUES ('m3', 'FA2 — Relational Databases & SQL', 40, 'Databases & Querying', 3, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m3-t1', 'm3', 'RDBMS Data Modeling', 'beginner', 2.5, ARRAY['Design ER diagrams for real-world scenarios', 'Define primary and foreign keys', 'Implement integrity constraints'], '{}'::text[], ARRAY['Design an ER diagram for an e-commerce system', 'Write CREATE TABLE with all constraint types'], 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m3-t1-s1', 'm3-t1', 'Entity-Relationships, Keys', 75, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m3-t1-s2', 'm3-t1', 'Integrity Constraints', 75, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m3-t2', 'm3', 'Normalization Engines', 'intermediate', 2.5, ARRAY['Identify normal form violations', 'Normalize tables through 3NF'], ARRAY['m3-t1'], ARRAY['Normalize an unnormalized student enrollment table to 3NF'], 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m3-t2-s1', 'm3-t2', 'Redundancy reduction', 60, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m3-t2-s2', 'm3-t2', '1NF, 2NF, 3NF rules', 90, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m3-t3', 'm3', 'SQL Schema Operations (DDL)', 'beginner', 1.5, ARRAY['Create and modify database schemas', 'Understand DDL vs DML'], ARRAY['m3-t1'], ARRAY['Create a database schema for a library system using DDL'], 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m3-t3-s1', 'm3-t3', 'CREATE, ALTER, DROP, TRUNCATE', 90, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m3-t4', 'm3', 'SQL Mutation Operations (DML)', 'beginner', 1.5, ARRAY['Insert, update, and delete data', 'Use WHERE clauses in mutations'], ARRAY['m3-t3'], ARRAY['Populate and modify data in the library schema'], 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m3-t4-s1', 'm3-t4', 'INSERT, UPDATE, DELETE', 90, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m3-t5', 'm3', 'Transaction Management (TCL)', 'intermediate', 2, ARRAY['Manage transactions with TCL commands', 'Explain ACID properties and their importance'], ARRAY['m3-t4'], ARRAY['Write transaction scripts with SAVEPOINT and ROLLBACK'], 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m3-t5-s1', 'm3-t5', 'COMMIT, ROLLBACK, SAVEPOINT', 60, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m3-t5-s2', 'm3-t5', 'ACID properties', 60, 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m3-t6', 'm3', 'Relational Querying', 'intermediate', 3, ARRAY['Write SELECT queries with filtering and grouping', 'Use aggregate functions with HAVING'], ARRAY['m3-t4'], ARRAY['Write reports using GROUP BY with HAVING filters'], 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m3-t6-s1', 'm3-t6', 'SELECT syntax, WHERE, GROUP BY, HAVING, ORDER BY', 180, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m3-t7', 'm3', 'Advanced Query Datasets (Joins)', 'intermediate', 3, ARRAY['Write all types of SQL JOINs', 'Choose the correct JOIN for a query requirement'], ARRAY['m3-t6'], ARRAY['Write 5 different JOIN queries on a multi-table employee database'], 7) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m3-t7-s1', 'm3-t7', 'Inner, Outer, Left, Right, Self Joins', 180, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.topics (id, module_id, name, difficulty, estimated_hours, learning_objectives, prerequisites, exercises, sort_order) VALUES ('m3-t8', 'm3', 'Complex Relations (Sub-queries)', 'intermediate-advanced', 3, ARRAY['Write nested and correlated sub-queries', 'Use aggregate functions in sub-queries'], ARRAY['m3-t7'], ARRAY['Find employees earning above department average using correlated sub-query'], 8) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m3-t8-s1', 'm3-t8', 'Nested & Correlated Sub-queries', 110, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.subtopics (id, topic_id, name, base_estimate_minutes, sort_order) VALUES ('m3-t8-s2', 'm3-t8', 'Aggregate functions: SUM, AVG, COUNT, MAX, MIN', 70, 2) ON CONFLICT (id) DO NOTHING;

COMMIT;

-- ── Verification ──
SELECT 'modules' AS tbl, count(*) FROM public.modules
UNION ALL SELECT 'topics', count(*) FROM public.topics
UNION ALL SELECT 'subtopics', count(*) FROM public.subtopics
UNION ALL SELECT 'assessments', count(*) FROM public.assessments;